Category Context and Reducer, Product Context And Reducer added
Mahi24-prog/e-commerce-react pull request #4
Opened 2022-04-02 05:54 UTC by Mahi24-prog

### Category Context and Reducer, Product Context And Reducer added
### Following Functionality Added
- Showing Products depend on category selected on home page
- All filters added 
- We can filters product by Price, Price high to low and low to high, Rating, Delivery, Out of stock, Clear

https://user-images.githubusercontent.com/59019169/161368667-08707b8e-021b-411c-a76e-c2010ba2c18f.mp4

2022-04-02 06:47 UTC, sakleprajwal approved these changes
Everything looks good please go ahead

2022-04-03 06:18 UTC, prathmeshjagtap requested changes
Else everything is good

2022-04-03 06:18 UTC, prathmeshjagtap commented on src/Components/Navbar/Navbar.jsx
> +            <img src='images/brand-logo.png' className='brand-logo'/>
add an alt tag to image

2022-04-03 06:18 UTC, prathmeshjagtap commented on src/Contexts/ProductContext.jsx
> +        console.log(response)
remove console.log

2022-04-03 06:18 UTC, prathmeshjagtap commented on src/Reducer/ProductReducer.jsx
> +            console.log(action.payload)
remove console.log

2022-04-03 06:22 UTC, Mahi24-prog commented on src/Contexts/ProductContext.jsx
> +        console.log(response)
ok

2022-04-03 06:22 UTC, prathmeshjagtap approved these changes

2022-04-03 06:22 UTC, Mahi24-prog commented on src/Reducer/ProductReducer.jsx
> +            console.log(action.payload)
ok

2022-04-03 06:22 UTC, merged